"""empty message

Revision ID: 6a78a8667cc4
Revises: 6b01625ca9a1
Create Date: 2025-05-22 02:45:36.570023

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6a78a8667cc4'
down_revision: str | None = '6b01625ca9a1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'settings',
        sa.Column('key', sa.VARCHAR(length=255), nullable=False),
        sa.Column('value', sa.VARCHAR(length=255), nullable=False),
        sa.Column('type', sa.VARCHAR(length=255), nullable=False),
        sa.PrimaryKeyConstraint('key', name=op.f('pk__settings')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
