"""empty message

Revision ID: 6b01625ca9a1
Revises: 
Create Date: 2025-05-21 18:33:41.409451

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b01625ca9a1'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'central',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            'created_at',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('temperature', sa.NUMERIC(precision=4, scale=1), nullable=False),
        sa.Column('humidity', sa.NUMERIC(precision=4, scale=1), nullable=False),
        sa.Column('pressure', sa.NUMERIC(precision=6, scale=1), nullable=False),
        sa.Column('co2', sa.INTEGER(), nullable=False),
        sa.Column('tvoc', sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk__central')),
    )
    op.create_table(
        'external_weather',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            'created_at',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('weather_description', sa.VARCHAR(length=255), nullable=False),
        sa.Column(
            'temperature_feels_like',
            sa.NUMERIC(precision=4, scale=1),
            nullable=False,
        ),
        sa.Column('precipitation', sa.NUMERIC(precision=4, scale=1), nullable=False),
        sa.Column('uv_index', sa.NUMERIC(precision=3, scale=1), nullable=False),
        sa.Column('wind_speed', sa.NUMERIC(precision=4, scale=1), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk__external_weather')),
    )
    op.create_table(
        'outdoor',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            'created_at',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('temperature', sa.NUMERIC(precision=4, scale=1), nullable=False),
        sa.Column('humidity', sa.NUMERIC(precision=4, scale=1), nullable=False),
        sa.Column('pressure', sa.NUMERIC(precision=6, scale=1), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk__outdoor')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outdoor')
    op.drop_table('external_weather')
    op.drop_table('central')
    # ### end Alembic commands ###
